version: '3.1'
services:
  pg-db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    networks:
      - ituz
    volumes:
      - ./postgres-db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
networks:
  ituz:
